GOLANGCI_LINT := go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.4

.PHONY: lint lint-fix

lint:
	cd anticheat && $(GOLANGCI_LINT) run ./...
	cd proxy && $(GOLANGCI_LINT) run ./...

lint-fix:
	cd anticheat && $(GOLANGCI_LINT) run --fix ./...
	cd proxy && $(GOLANGCI_LINT) run --fix ./...
