package utils

import (
	"iter"
	"math"
	_ "unsafe"

	"github.com/chewxy/math32"
	"github.com/df-mc/dragonfly/server/block"
	"github.com/df-mc/dragonfly/server/block/cube"
	"github.com/df-mc/dragonfly/server/world"
	"github.com/oomph-ac/bedsim"
	"github.com/oomph-ac/oomph/anticheat/game"
	"github.com/oomph-ac/oomph/anticheat/utils/collisions"
	"github.com/oomph-ac/oomph/anticheat/world/blockmodel"
	"github.com/sandertv/gophertunnel/minecraft/protocol"
)

type BlockSearchResult struct {
	Block    world.Block
	Position cube.Pos
}

// BlockFriction returns the friction of the block.
func BlockFriction(b world.Block) float32 {
	if f, ok := b.(block.Frictional); ok {
		return float32(f.Friction())
	}

	switch bedsim.BlockName(b) {
	case "minecraft:slime":
		return 0.8
	case "minecraft:ice", "minecraft:packed_ice":
		return 0.98
	case "minecraft:blue_ice":
		return 0.99
	default:
		return 0.6
	}
}

// CanPassBlock returns true if an entity can pass through the given block.
func CanPassBlock(b world.Block) bool {
	switch bedsim.BlockName(b) {
	case "minecraft:web", "minecraft:water", "minecraft:lava":
		return true
	default:
		return false
	}
}

// OneWayCollisionBlocks returns an array of blocks that utilize one-way physics.
func OneWayCollisionBlocks(blocks []BlockSearchResult) []world.Block {
	oneWayBlocks := []world.Block{}
	for _, b := range blocks {
		if BlockClimbable(b.Block) {
			oneWayBlocks = append(oneWayBlocks, b.Block)
		}
	}

	return oneWayBlocks
}

// BlockCollisions returns the bounding boxes of the given block based on it's name.
func BlockCollisions(b world.Block, pos cube.Pos, src world.BlockSource) []cube.BBox32 {
	// If the block is not registered by Dragonfly, fallback to collision definitions generated by PrismarineJS
	if x, y := b.Hash(); x == 0 && y == math.MaxUint64 {
		return collisions.ForBlock(b)
	}

	switch b.(type) {
	case block.Wall, block.WoodFence, block.NetherBrickFence, block.IronBars, block.GlassPane, block.StainedGlassPane:
		// TODO: Have these bounding boxes fixed in DF
		return collisions.ForBlock(b)
	}

	var bModel = b.Model()
	if _, isIronBar := b.(block.IronBars); isIronBar {
		bModel = blockmodel.IronBars{}
	}

	dfBoxes := bModel.BBox(cube.Pos(pos), src)
	switch len(dfBoxes) {
	case 0:
		return nil
	case 1:
		return []cube.BBox32{game.BBox32FromBBox(dfBoxes[0])}
	}

	boxes := make([]cube.BBox32, len(dfBoxes))
	for i, bb := range dfBoxes {
		boxes[i] = game.BBox32FromBBox(bb)
	}
	return boxes
}

// BlocksInRadius returns a list of block positions within a radius of the given position.
func BlocksInRadius(pos protocol.BlockPos, radius int32) []protocol.BlockPos {
	blocks := []protocol.BlockPos{}
	for x := -radius; x <= radius; x++ {
		for y := -radius; y <= radius; y++ {
			for z := -radius; z <= radius; z++ {
				blocks = append(blocks, protocol.BlockPos{pos[0] + x, pos[1] + y, pos[2] + z})
			}
		}
	}
	return blocks
}

// NearbyBlockCollisions ...
func NearbyBlockCollisions(aabb cube.BBox32, src world.BlockSource) iter.Seq[BlockSearchResult] {
	return func(yield func(BlockSearchResult) bool) {
		min, max := aabb.Min(), aabb.Max()
		minX, minY, minZ := int(math32.Floor(min[0])), int(math32.Floor(min[1])), int(math32.Floor(min[2]))
		maxX, maxY, maxZ := int(math32.Ceil(max[0])), int(math32.Ceil(max[1])), int(math32.Ceil(max[2]))
		for y := minY; y <= maxY; y++ {
			for x := minX; x <= maxX; x++ {
				for z := minZ; z <= maxZ; z++ {
					pos := cube.Pos{x, y, z}
					b := src.Block(cube.Pos(pos))
					if _, isAir := b.(block.Air); isAir {
						continue
					}

					// Add the block to the list of block search results.
					vecPos := game.BlockPosVec3(pos)
				block_loop:
					for _, bb := range BlockCollisions(b, pos, src) {
						if bb.Translate(vecPos).IntersectsWith(aabb) {
							if !yield(BlockSearchResult{Block: b, Position: pos}) {
								return
							}
							break block_loop
						}
					}
				}
			}
		}
	}
}

// NearbyBlocks get the blocks that are within a range of the provided bounding box.
func NearbyBlocks(aabb cube.BBox32, includeAir bool, includeUnknown bool, src world.BlockSource) iter.Seq[BlockSearchResult] {
	return func(yield func(BlockSearchResult) bool) {
		min, max := aabb.Min(), aabb.Max()
		minX, minY, minZ := int(math32.Floor(min[0])), int(math32.Floor(min[1])), int(math32.Floor(min[2]))
		maxX, maxY, maxZ := int(math32.Ceil(max[0])), int(math32.Ceil(max[1])), int(math32.Ceil(max[2]))

		for y := minY; y <= maxY; y++ {
			for x := minX; x <= maxX; x++ {
				for z := minZ; z <= maxZ; z++ {
					pos := cube.Pos{x, y, z}
					b := src.Block(cube.Pos(pos))
					if _, isAir := b.(block.Air); !includeAir && isAir {
						b = nil
						continue
					}

					// If the hash is MaxUint64, then the block is unknown to dragonfly.
					bHash, _ := b.Hash()
					if !includeUnknown && bHash == math.MaxUint64 {
						b = nil
						continue
					}

					if !yield(BlockSearchResult{Block: b, Position: pos}) {
						return
					}
				}
			}
		}
	}
}

// HasNearbyBBoxes returns true if there's at least one bounding box within the given bounding box.
func HasNearbyBBoxes(aabb cube.BBox32, src world.BlockSource) bool {
	_, found := scanNearbyBBoxes(aabb, src, true)
	return found
}

// NearbyBBoxes returns a list of block bounding boxes that are within the given bounding box.
func NearbyBBoxes(aabb cube.BBox32, src world.BlockSource) []cube.BBox32 {
	bboxList, _ := scanNearbyBBoxes(aabb, src, false)
	return bboxList
}

func scanNearbyBBoxes(aabb cube.BBox32, src world.BlockSource, firstOnly bool) ([]cube.BBox32, bool) {
	grown := aabb.Grow(1.0)
	min, max := grown.Min(), grown.Max()
	minX, minY, minZ := int(math32.Floor(min[0])), int(math32.Floor(min[1])), int(math32.Floor(min[2]))
	maxX, maxY, maxZ := int(math32.Ceil(max[0])), int(math32.Ceil(max[1])), int(math32.Ceil(max[2]))

	var bboxList []cube.BBox32
	maxIters := (maxX - minX + 1) * (maxY - minY + 1) * (maxZ - minZ + 1)

	for x := minX; x <= maxX; x++ {
		for z := minZ; z <= maxZ; z++ {
			for y := minY; y <= maxY; y++ {
				pos := cube.Pos{x, y, z}
				block := src.Block(cube.Pos(pos))
				if CanPassBlock(block) {
					continue
				}

				posVec := game.BlockPosVec3(pos)
				for _, box := range BlockCollisions(block, pos, src) {
					b := box.Translate(posVec)
					if !b.IntersectsWith(aabb) {
						continue
					}
					if firstOnly {
						return nil, true
					}
					if bboxList == nil {
						bboxList = make([]cube.BBox32, 0, maxIters)
					}
					bboxList = append(bboxList, b)
				}
			}
		}
	}

	return bboxList, false
}

// BlockClimbable returns whether the given block is climbable.
func BlockClimbable(b world.Block) bool {
	switch b.(type) {
	case block.Ladder:
		return true
	}

	switch bedsim.BlockName(b) {
	case "minecraft:vine", "minecraft:cave_vines", "minecraft:cave_vines_body_with_berries", "minecraft:cave_vines_head_with_berries",
		"minecraft:twisting_vines", "minecraft:weeping_vines":
		return true
	default:
		return false
	}
}

// IsFence returns true if the block is a fence.
func IsFence(b world.Block) bool {
	switch b.(type) {
	case block.WoodFence, block.NetherBrickFence:
		return true
	default:
		return false
	}
}

// IsFenceGate returns true if the block is a fence gate
func IsFenceGate(b world.Block) bool {
	_, ok := b.(block.WoodFenceGate)
	return ok
}

// IsWall returns true if the block is a wall.
func IsWall(b world.Block) bool {
	_, ok := b.(block.Wall)
	return ok
}

// IsBlockPassInteraction returns true if the block allows interactions although it has a solid
// collision bounding box.
func IsBlockPassInteraction(b world.Block) bool {
	switch bedsim.BlockName(b) {
	case "minecraft:barrier", "minecraft:invisible_bedrock":
		return true
	default:
		return false
	}
}

// BlockToCubePos converts protocol.BlockPos into cube.Pos.
func BlockToCubePos(p [3]int32) cube.Pos {
	return cube.Pos{int(p[0]), int(p[1]), int(p[2])}
}

func IsBlockPlaceAlwaysSimBased(b world.Item) bool {
	switch b.(type) {
	case block.Vines, block.Ladder:
		return true
	}
	return false
}
