package player

import (
	"context"
	"io"
	"net"
	"time"

	"github.com/df-mc/dragonfly/server/world"
	playercontext "github.com/oomph-ac/oomph/player/context"
	"github.com/sandertv/gophertunnel/minecraft"
	"github.com/sandertv/gophertunnel/minecraft/protocol/login"
	"github.com/sandertv/gophertunnel/minecraft/protocol/packet"
)

// Conn returns the connection to the client.
func (p *Player) Conn() *minecraft.Conn {
	return p.conn
}

// ServerConn returns the connection to the server.
func (p *Player) ServerConn() ServerConn {
	return p.serverConn
}

// SetConn sets the connection to the client.
func (p *Player) SetConn(conn *minecraft.Conn) {
	p.conn = conn

	p.RuntimeId = conn.GameData().EntityRuntimeID
	p.UniqueId = conn.GameData().EntityUniqueID

	p.ClientDat = conn.ClientData()
	p.IdentityDat = conn.IdentityData()
	p.GameDat = conn.GameData()
	p.Version = conn.Proto().ID()
}

// SetServerConn sets the connection to the server.
func (p *Player) SetServerConn(conn ServerConn) {
	if conn == nil {
		p.Disconnect("<red>Proxy was unable to complete transfer to remote server.</red>")
		return
	}

	if p.serverConn == nil {
		for _, item := range conn.GameData().Items {
			if i, ok := world.ItemByName(item.Name, 0); ok {
				p.items[item.RuntimeID] = i
			}
		}
	}

	p.GameDat = conn.GameData()
	p.serverConn = conn
	p.RuntimeId = conn.GameData().EntityRuntimeID
	p.UniqueId = conn.GameData().EntityUniqueID
	p.GameMode = conn.GameData().PlayerGameMode
	if p.GameMode == 5 {
		p.GameMode = conn.GameData().WorldGameMode
	}

	p.PendingCorrectionACK = false
	p.acks.ResetTransferState()
	p.movement.ResetTransferState(p.GameDat.PlayerPosition)
}

// ChunkRadius returns the chunk radius as requested by the client at the other end of the conn.
func (p *Player) ChunkRadius() int {
	return p.conn.ChunkRadius()
}

// ClientCacheEnabled specifies if the conn has the client cache, used for caching chunks client-side, enabled or
// not. Some platforms, like the Nintendo Switch, have this disabled at all times.
func (p *Player) ClientCacheEnabled() bool {
	// todo: support client cache
	//return p.conn.ClientCacheEnabled()
	return false
}

// ReadPacket reads a packet from the connection. When Oomph is embedded in a
// Dragonfly server, packets generated by Oomph are returned before reading the
// next client packet and cancelled client packets are suppressed.
func (p *Player) ReadPacket() (packet.Packet, error) {
	if p.directMode {
		return p.readDirectPacket()
	}
	return p.conn.ReadPacket()
}

// WritePacket writes a packet to the connection. In embedded Dragonfly mode,
// server packets pass through Oomph before being sent to the client.
func (p *Player) WritePacket(pk packet.Packet) error {
	if p.directMode {
		ctx := playercontext.NewHandlePacketContext(&pk)
		p.HandleServerPacket(ctx)
		if ctx.Cancelled() {
			return nil
		}
		pk = *ctx.Packet()
	}
	return p.conn.WritePacket(pk)
}

type packetRead struct {
	pk  packet.Packet
	err error
}

// EnableDirectMode configures the player as Dragonfly's session connection.
// It must be called after SetConn and before the connection is returned to
// Dragonfly.
func (p *Player) EnableDirectMode() {
	p.directOnce.Do(func() {
		p.directMode = true
		p.directNotify = make(chan struct{}, 1)
		p.directReads = make(chan packetRead)
		go p.readDirectClientPackets()
	})
}

func (p *Player) readDirectClientPackets() {
	for {
		pk, err := p.conn.ReadPacket()
		select {
		case p.directReads <- packetRead{pk: pk, err: err}:
		case <-p.CloseChan:
			return
		}
		if err != nil {
			return
		}
	}
}

func (p *Player) readDirectPacket() (packet.Packet, error) {
	for {
		if pk, ok := p.popDirectPacket(); ok {
			return pk, nil
		}
		select {
		case <-p.directNotify:
			continue
		case result := <-p.directReads:
			if result.err != nil {
				return nil, result.err
			}
			ctx := playercontext.NewHandlePacketContext(&result.pk)
			p.HandleClientPacket(ctx)
			if ctx.Cancelled() {
				continue
			}
			return *ctx.Packet(), nil
		case <-p.CloseChan:
			return nil, io.EOF
		}
	}
}

func (p *Player) enqueueDirectPacket(pk packet.Packet) {
	p.directMu.Lock()
	p.directPackets = append(p.directPackets, pk)
	p.directMu.Unlock()
	select {
	case p.directNotify <- struct{}{}:
	default:
	}
}

func (p *Player) popDirectPacket() (packet.Packet, bool) {
	p.directMu.Lock()
	defer p.directMu.Unlock()
	if len(p.directPackets) == 0 {
		return nil, false
	}
	pk := p.directPackets[0]
	copy(p.directPackets, p.directPackets[1:])
	p.directPackets[len(p.directPackets)-1] = nil
	p.directPackets = p.directPackets[:len(p.directPackets)-1]
	return pk, true
}

// IdentityData returns the login.IdentityData of a player. It contains the UUID, XUID and username of the connection.
func (p *Player) IdentityData() login.IdentityData {
	return p.conn.IdentityData()
}

// ClientData returns the login.ClientData of a player. This includes less sensitive data of the player like its skin,
// language code and other non-essential information.
func (p *Player) ClientData() login.ClientData {
	return p.conn.ClientData()
}

// Flush flushes the packets buffered by the conn, sending all of them out immediately.
func (p *Player) Flush() error {
	if p.conn == nil {
		return nil
	}
	return p.conn.Flush()
}

// RemoteAddr returns the remote network address.
func (p *Player) RemoteAddr() net.Addr {
	return p.conn.RemoteAddr()
}

// Latency returns the current latency measured over the conn.
func (p *Player) Latency() time.Duration {
	return p.conn.Latency()
}

// StartGameContext starts the game for the conn with a context to cancel it.
func (p *Player) StartGameContext(ctx context.Context, data minecraft.GameData) error {
	//data.PlayerMovementSettings.MovementType = protocol.PlayerMovementModeServerWithRewind
	data.PlayerMovementSettings.RewindHistorySize = 100
	if err := p.conn.StartGameContext(ctx, data); err != nil {
		return err
	}
	if p.directMode {
		p.applyDirectGameData(data)
		go p.StartTicking()
	}
	return nil
}

func (p *Player) applyDirectGameData(data minecraft.GameData) {
	p.GameDat = data
	p.RuntimeId = 1
	p.UniqueId = data.EntityUniqueID
	p.GameMode = data.PlayerGameMode
	if p.GameMode == 5 {
		p.GameMode = data.WorldGameMode
	}
	if p.movement != nil {
		p.movement.ResetTransferState(data.PlayerPosition)
	}
}
